import { ChangedBookings } from '../persistence/persistence.js';
import { MonthAvailabilities } from '../types.js';

export function generateEmailBody(
  datesInterested: string[],
  newAvailabilities: ChangedBookings,
  allAvailabilities: MonthAvailabilities,
): string {
  const { newBookings, newCancellations } = newAvailabilities;

  const totalNewBookings = countAvailabilities(newBookings);
  const totalCancellations = countAvailabilities(newCancellations);

  return `<h3>Update - New Cancellations (${totalCancellations}) / New Bookings (${totalNewBookings})</h3>
    <p>
      A new report has been generated by Sensea Scanner. Please see changes in availabilities as listed below. <a href="https://sensea.as.me/schedule.php">Click here</a> to make a booking.
    </p>
    <p>
      Your Sensea Scanner is monitoring the following dates: ${datesInterested.join(
        ', ',
      )}
    </p>
    <p>
      <h3>New cancellations:</h3>
      ${formatAvailabilityList(newCancellations)} 
    </p>
    <p>
      <h3>New bookings:</h3> 
      ${formatAvailabilityList(newBookings)}
    </p>
    <p>
      <h3>All availabilities for dates interested in:</h3>
      ${formatAvailabilityList(allAvailabilities)}
    </p>
    `;
}

function countAvailabilities(monthAvailabilities: MonthAvailabilities): number {
  const datesAvailabilitiesEntries = Object.entries(monthAvailabilities);
  return datesAvailabilitiesEntries.reduce(
    (acc, [_, dateAvailabilities]) =>
      acc + Object.keys(dateAvailabilities).length,
    0,
  );
}

function formatAvailabilityList(
  monthAvailabilites: MonthAvailabilities,
): string {
  const datesAvailabilitesEntries = Object.entries(monthAvailabilites);

  return `<ul>
    ${datesAvailabilitesEntries
      .map(
        ([date, timeslot]) =>
          `<li> ${date} 
        <ul>
        ${Object.entries(timeslot)
          .map(
            ([dateTime, { slotsAvailable }]) =>
              `<li>${new Date(dateTime).toLocaleTimeString('en-US', {
                hour12: true,
                hour: 'numeric',
                minute: '2-digit',
                second: '2-digit',
              })}: ${slotsAvailable}</li>`,
          )
          .join('')}
        </ul>
        </li>`,
      )
      .join('')}
    </ul>`;
}
